# Apply Day 2 Configuration
- name: Apply Day 2 Configuration to OpenShift Cluster
  hosts: localhost
  vars_files:
    - ../group_vars/all.yaml
  vars: 
    ansible_python_interpreter: "/your/path/to/venv/bin/python3"
  gather_facts: false
  roles:
    - install_openshift_gitops
