---
# ArgoCD Application Configuration
odf_argocd_app_name: "odf-storage"
odf_argocd_namespace: "openshift-gitops"
odf_argocd_project: "default"
odf_argocd_sync_policy: "Automatic"

# Git repo URL (HTTPS); from arg_gitops_repo / gitops_repo_url
odf_git_repo_url: "{{ gitops_repo_url }}"
odf_git_repo_path: "odf"
odf_git_repo_revision: "main"

# Target Namespace for ODF deployment
odf_target_namespace: "openshift-storage"