apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    creationTimestamp: '2026-03-16T21:21:51Z'
    managedFields:
    -   apiVersion: rbac.authorization.k8s.io/v1
        fieldsType: FieldsV1
        fieldsV1:
            f:roleRef: {}
            f:subjects: {}
        manager: OpenAPI-Generator
        operation: Update
        time: '2026-03-16T21:21:51Z'
    name: openshift-gitops-acm-admin
    resourceVersion: '280794'
    uid: f54f8efc-dfc9-4c02-9036-17dd13a1c34a
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
-   kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
