apiVersion: v1
data:
    project: YWNt
    sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCbEJ0QjNzM1RkeXBBSGxXYlJmWUdhb0E1aXYvN0wrQ1h0OTlINEdmR1RtUUFBQUpqc3lLdk83TWlyCnpnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQmxCdEIzczNUZHlwQUhsV2JSZllHYW9BNWl2LzdMK0NYdDk5SDRHZkdUbVEKQUFBRUM5aGdLSU1vb2NpbmNJTG1LVi91NXVhRkZHdEsrVDNnR0xMR1Yyam1VOXJHVUcwSGV6ZE4zS2tBZVZadEY5Z1pxZwpEbUsvL3N2NEplMzMwZmdaOFpPWkFBQUFFV054ZFdsdmJrQnlaV1JvWVhRdVkyOXRBUUlEQkE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
    type: Z2l0
    url: Z2l0QGdpdGh1Yi5jb206U2t5bGFyU2NhbGluZy9naXRvcHMtaW5zdGFsbC1hY20uZ2l0
kind: Secret
metadata:
    creationTimestamp: '2026-03-16T22:27:10Z'
    labels:
        argocd.argoproj.io/secret-type: repository
    managedFields:
    -   apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
            f:data:
                .: {}
                f:project: {}
                f:sshPrivateKey: {}
                f:type: {}
                f:url: {}
            f:metadata:
                f:labels:
                    .: {}
                    f:argocd.argoproj.io/secret-type: {}
            f:type: {}
        manager: OpenAPI-Generator
        operation: Update
        time: '2026-03-17T13:59:35Z'
    name: gitops-install-acm-repo-secret
    namespace: openshift-gitops
    resourceVersion: '519610'
    uid: 9a7246d5-abe7-4b0c-bf77-34e52f5a4092
type: Opaque
