---
- name: Install Day 2 Config via OpenShift GitOps (ArgoCD)
  hosts: localhost
  vars_files:
    - ../group_vars/all.yaml
    - secrets.yml
  connection: local
  gather_facts: false
  vars: 
    ansible_python_interpreter: /Users/chrisquion/5873302-acm-observability/ansible-k8s-venv/.ansible-k8s/bin/python3
  roles:
    - role: configure_argo
    - role: apps_install_acm
